name: virtualpruning
channels:
  - fredboudon
  - conda-forge
dependencies:
  - openalea.lpy=3.*
  - openalea.plantgl=3.*
  - openalea.mtg
  - alinea.caribu
  - alinea.astk
  - jupyterlab>=3.*
  - jupyterlab_widgets
  - ipython=7
  - matplotlib
  - numpy=1.20.*
  - pandas
  - scipy
  - pip
  - nodejs
  - pip:
    - pgljupyter>=1.1.*
